# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\david\Desktop\singidunum\noSQL\qtDesignerIzgled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from distutils.log import error
from sqlite3 import connect
from PyQt5 import QtCore, QtGui, QtWidgets
import functions
import mysql.connector
from mysql.connector import errorcode

class ConnectDatabaseWindow(QtWidgets.QWidget):
    #pojednostaviti kod 
    def __init__(self):
        super().__init__()
        layout = QtWidgets.QVBoxLayout()
        self.resize(405, 300)
        self.host_label = QtWidgets.QLabel("Host:")
        self.input_host = QtWidgets.QLineEdit(self)
        self.user_label = QtWidgets.QLabel("User:")
        self.input_user = QtWidgets.QLineEdit(self)
        self.password_label = QtWidgets.QLabel("Password:")
        self.input_password = QtWidgets.QLineEdit(self)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.button = QtWidgets.QPushButton(self)
        self.button.setGeometry(QtCore.QRect(0, 50, 120, 28))
        self.button.setText("Connect")
        self.button.clicked.connect(self.connect)
        layout.addWidget(self.host_label)
        layout.addWidget(self.input_host)
        layout.addWidget(self.user_label)
        layout.addWidget(self.input_user)
        layout.addWidget(self.password_label)
        layout.addWidget(self.input_password)
        layout.addSpacing(10)
        layout.addWidget(self.button)
        self.setLayout(layout)

    def connect(self):
        try: 
            mydb = mysql.connector.connect(host= self.input_host.text(), user= self.input_user.text(), password = self.input_password.text())
            print("Database connected.")
        except mysql.connector.Error as err:
            #dodati error window
            if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                print("Something is wrong.")
            elif err.errno == errorcode.ER_BAD_DB_ERROR:
                print("Database does not exist.")
            else:
                print(err)
        else:
            mydb.close()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.mainComboBox.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.mainComboBox.setCurrentText("")
        self.mainComboBox.setMaxVisibleItems(21)
        self.mainComboBox.setObjectName("mainComboBox")
        self.mainTabLine = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabLine.setGeometry(QtCore.QRect(0, 50, 801, 551))
        self.mainTabLine.setObjectName("mainTabLine")
        self.connectionTab = QtWidgets.QWidget()
        self.connectionTab.setObjectName("connectionTab")
        self.loadAndConnectButton = QtWidgets.QPushButton(self.connectionTab)
        self.loadAndConnectButton.setGeometry(QtCore.QRect(-10, 210, 811, 28))
        self.loadAndConnectButton.setObjectName("loadAndConnectButton")
        #Connect Database function:
        self.loadAndConnectButton.clicked.connect(self.show_connect_database)

        self.mainTabLine.addTab(self.connectionTab, "")
        self.databasesTab = QtWidgets.QWidget()
        self.databasesTab.setObjectName("databasesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.databasesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 801, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.databaseNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.databaseNameLabel.setObjectName("databaseNameLabel")
        self.horizontalLayout.addWidget(self.databaseNameLabel)
        self.databaseNameInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.databaseNameInput.setObjectName("databaseNameInput")
        self.horizontalLayout.addWidget(self.databaseNameInput)
        self.createDatabaseButton = QtWidgets.QPushButton(self.databasesTab)
        self.createDatabaseButton.setGeometry(QtCore.QRect(0, 50, 141, 28))
        self.createDatabaseButton.setObjectName("createDatabaseButton")
        self.deleteSelectedDatabaseButton = QtWidgets.QPushButton(self.databasesTab)
        self.deleteSelectedDatabaseButton.setGeometry(QtCore.QRect(150, 50, 181, 28))
        self.deleteSelectedDatabaseButton.setObjectName("deleteSelectedDatabaseButton")
        self.databasesTableWidget = QtWidgets.QTableWidget(self.databasesTab)
        self.databasesTableWidget.setGeometry(QtCore.QRect(0, 80, 801, 441))
        self.databasesTableWidget.setObjectName("databasesTableWidget")
        self.databasesTableWidget.setColumnCount(0)
        self.databasesTableWidget.setRowCount(0)
        self.mainTabLine.addTab(self.databasesTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.dataTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 801, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.dataTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 801, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.insertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.insertButton.setObjectName("insertButton")
        self.horizontalLayout_3.addWidget(self.insertButton)
        self.updateSelectedButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.updateSelectedButton.setObjectName("updateSelectedButton")
        self.horizontalLayout_3.addWidget(self.updateSelectedButton)
        self.deleteSelectedButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.horizontalLayout_3.addWidget(self.deleteSelectedButton)
        self.getAllButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.getAllButton.setObjectName("getAllButton")
        self.horizontalLayout_3.addWidget(self.getAllButton)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.tableView = QtWidgets.QTableView(self.dataTab)
        self.tableView.setGeometry(QtCore.QRect(0, 110, 791, 411))
        self.tableView.setObjectName("tableView")
        self.mainTabLine.addTab(self.dataTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabLine.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def show_connect_database(self):
        print("sssss")
        self.w = ConnectDatabaseWindow()
        self.w.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmartMan"))
        self.loadAndConnectButton.setText(_translate("MainWindow", "Load and Connect Database"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.connectionTab), _translate("MainWindow", "Connection"))
        self.databaseNameLabel.setText(_translate("MainWindow", "Enter Database Name:"))
        self.createDatabaseButton.setText(_translate("MainWindow", "Create Database"))
        self.deleteSelectedDatabaseButton.setText(_translate("MainWindow", "Delete Selected Database"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.databasesTab), _translate("MainWindow", "Databases"))
        self.label_2.setText(_translate("MainWindow", "Database:"))
        self.label.setText(_translate("MainWindow", "Collection:"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.updateSelectedButton.setText(_translate("MainWindow", "Update Selected"))
        self.deleteSelectedButton.setText(_translate("MainWindow", "Delete Selected"))
        self.getAllButton.setText(_translate("MainWindow", "Get All"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.dataTab), _translate("MainWindow", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

