from PyQt5 import QtCore, QtGui, QtWidgets

from main_window_controller import MainWindowController


class MainWindowViewer(object):
    def __init__(self):
        self.main_window_controller = MainWindowController()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.mainComboBox.setGeometry(QtCore.QRect(2, 0, 800, 41))
        self.mainComboBox.setCurrentText("")
        self.mainComboBox.addItem("MySQL")
        self.mainComboBox.addItem("MongoDB")
        self.mainComboBox.addItem("ArangoDB")
        self.mainComboBox.setMaxVisibleItems(21)
        self.mainComboBox.setObjectName("mainComboBox")
        self.mainTabLine = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabLine.setGeometry(QtCore.QRect(2, 50, 800, 551))
        self.mainTabLine.setObjectName("mainTabLine")
        self.connectionTab = QtWidgets.QWidget()
        self.connectionTab.setObjectName("connectionTab")
        self.loadAndConnectButton = QtWidgets.QPushButton(self.connectionTab)
        self.loadAndConnectButton.setGeometry(QtCore.QRect(-10, 210, 811, 28))
        self.loadAndConnectButton.setObjectName("loadAndConnectButton")

        self.mainTabLine.addTab(self.connectionTab, "")
        self.databasesTab = QtWidgets.QWidget()
        self.databasesTab.setObjectName("databasesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.databasesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 801, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.EnterDatabaseNameHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.EnterDatabaseNameHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.EnterDatabaseNameHorizontalLayout.setObjectName("EnterDatabaseNameHorizontalLayout")
        self.databaseNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.databaseNameLabel.setObjectName("databaseNameLabel")
        self.EnterDatabaseNameHorizontalLayout.addWidget(self.databaseNameLabel)
        self.databaseNameInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.databaseNameInput.setObjectName("databaseNameInput")
        self.EnterDatabaseNameHorizontalLayout.addWidget(self.databaseNameInput)
        self.createDatabaseButton = QtWidgets.QPushButton(self.databasesTab)
        self.createDatabaseButton.setGeometry(QtCore.QRect(0, 50, 141, 28))
        self.createDatabaseButton.setObjectName("createDatabaseButton")
        self.deleteSelectedDatabaseButton = QtWidgets.QPushButton(self.databasesTab)
        self.deleteSelectedDatabaseButton.setGeometry(QtCore.QRect(150, 50, 181, 28))
        self.deleteSelectedDatabaseButton.setObjectName("deleteSelectedDatabaseButton")
        self.databasesTableWidget = QtWidgets.QTableWidget(self.databasesTab)
        self.databasesTableWidget.setGeometry(QtCore.QRect(0, 80, 801, 441))
        self.databasesTableWidget.setObjectName("databasesTableWidget")
        self.databasesTableWidget.setColumnCount(0)
        self.databasesTableWidget.setRowCount(0)
        self.databasesTableWidget.setSortingEnabled(True)
        self.mainTabLine.addTab(self.databasesTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.dataTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 801, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.databaseAndCollectionHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.databaseAndCollectionHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.databaseAndCollectionHorizontalLayout.setObjectName("databaseAndCollectionHorizontalLayout")
        self.databaseSelectLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.databaseSelectLabel.setEnabled(True)
        self.databaseSelectLabel.setObjectName("databaseSelectLabel")
        self.databaseAndCollectionHorizontalLayout.addWidget(self.databaseSelectLabel)
        self.databasesComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.databasesComboBox.setObjectName("databasesComboBox")

        self.databaseAndCollectionHorizontalLayout.addWidget(self.databasesComboBox)
        self.collectionSelectLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.collectionSelectLabel.setObjectName("collectionSelectLabel")
        self.databaseAndCollectionHorizontalLayout.addWidget(self.collectionSelectLabel)
        self.collectionsComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.collectionsComboBox.setObjectName("collectionsComboBox")
        self.databaseAndCollectionHorizontalLayout.addWidget(self.collectionsComboBox)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.dataTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 801, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.databaseCRUDHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.databaseCRUDHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.databaseCRUDHorizontalLayout.setObjectName("databaseCRUDHorizontalLayout")
        self.insertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.insertButton.setObjectName("insertButton")
        self.databaseCRUDHorizontalLayout.addWidget(self.insertButton)
        self.updateSelectedButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.updateSelectedButton.setObjectName("updateSelectedButton")
        self.databaseCRUDHorizontalLayout.addWidget(self.updateSelectedButton)
        self.deleteSelectedButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.databaseCRUDHorizontalLayout.addWidget(self.deleteSelectedButton)
        self.getAllButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.getAllButton.setObjectName("getAllButton")
        self.databaseCRUDHorizontalLayout.addWidget(self.getAllButton)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.searchButton.setObjectName("searchButton")
        self.databaseCRUDHorizontalLayout.addWidget(self.searchButton)

        self.databaseDataTableWidget = QtWidgets.QTableWidget(self.dataTab)
        self.databaseDataTableWidget.setGeometry(QtCore.QRect(0, 110, 791, 411))
        self.databaseDataTableWidget.setObjectName("databaseDataTableWidget")
        self.databaseDataTableWidget.setColumnCount(0)
        self.databaseDataTableWidget.setRowCount(0)

        self.mainTabLine.addTab(self.dataTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabLine.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # connections
        # Connection tab
        self.loadAndConnectButton.clicked.connect(lambda x: self.main_window_controller.load_and_connect_db(self.databasesTableWidget, self.databasesComboBox, self.statusbar))
        
        # Databases tab
        self.createDatabaseButton.clicked.connect(lambda x: self.main_window_controller.create_database(self.databaseNameInput.text(), self.statusbar, self.databasesComboBox, self.databasesTableWidget))
        self.deleteSelectedDatabaseButton.clicked.connect(lambda x: self.main_window_controller.delete_selected_database(self.databasesTableWidget, self.databasesComboBox, self.statusbar))

        # Data tab
        self.databasesComboBox.currentIndexChanged.connect(lambda y: self.main_window_controller.load_collections(self.databasesComboBox.currentText(), self.collectionsComboBox))
        self.getAllButton.clicked.connect(lambda y: self.main_window_controller.load_table_data(self.collectionsComboBox.currentText(), self.databaseDataTableWidget))
        self.deleteSelectedButton.clicked.connect(lambda y: self.main_window_controller.delete_row(self.databaseDataTableWidget, self.databasesComboBox.currentText(), self.collectionsComboBox.currentText()))
        self.insertButton.clicked.connect(lambda y: self.main_window_controller.show_data_handler_dialog(self.databasesComboBox.currentText(), self.collectionsComboBox.currentText(), "insert", self.databaseDataTableWidget, self.statusbar))
        self.updateSelectedButton.clicked.connect(lambda y: self.main_window_controller.show_data_handler_dialog(self.databasesComboBox.currentText(), self.collectionsComboBox.currentText(), "update", self.databaseDataTableWidget, self.statusbar))
        self.searchButton.clicked.connect(lambda y: self.main_window_controller.show_data_handler_dialog(self.databasesComboBox.currentText(), self.collectionsComboBox.currentText(), "search", self.databaseDataTableWidget, self.statusbar))
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmartMan"))
        self.loadAndConnectButton.setText(_translate("MainWindow", "Load and Connect Database"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.connectionTab), _translate("MainWindow", "Connection"))
        self.databaseNameLabel.setText(_translate("MainWindow", "Enter Database Name:"))
        self.createDatabaseButton.setText(_translate("MainWindow", "Create Database"))
        self.deleteSelectedDatabaseButton.setText(_translate("MainWindow", "Delete Selected Database"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.databasesTab), _translate("MainWindow", "Databases"))
        self.databaseSelectLabel.setText(_translate("MainWindow", "Database:"))
        self.collectionSelectLabel.setText(_translate("MainWindow", "Collection:"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.updateSelectedButton.setText(_translate("MainWindow", "Update Selected"))
        self.deleteSelectedButton.setText(_translate("MainWindow", "Delete Selected"))
        self.getAllButton.setText(_translate("MainWindow", "Get All"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.mainTabLine.setTabText(self.mainTabLine.indexOf(self.dataTab), _translate("MainWindow", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainWindowViewer()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
